/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author nguye
 */
public class ViewPanelManage extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanelManage
     */
    public ViewPanelManage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPaneMain = new javax.swing.JTabbedPane();
        viewPanelProduct = new view.ViewPanelProduct();
        viewPanelCategory = new view.ViewPanelCategory();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        setLayout(new javax.swing.OverlayLayout(this));

        tabPaneMain.addTab("Sản phẩm", viewPanelProduct);
        tabPaneMain.addTab("Loại sản phẩm", viewPanelCategory);

        add(tabPaneMain);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabPaneMain;
    private view.ViewPanelCategory viewPanelCategory;
    private view.ViewPanelProduct viewPanelProduct;
    // End of variables declaration//GEN-END:variables

    public ViewPanelCategory getViewPanelCategory() {
        return viewPanelCategory;
    }

    public ViewPanelProduct getViewPanelProduct() {
        return viewPanelProduct;
    }
}
